"""
Auto-generated Category Keywords
Generated from Categories & subs.xlsx
DO NOT EDIT MANUALLY - Use keyword_generator.py to regenerate
"""

CATEGORY_KEYWORDS = {
    "Alcoholic Beverages": {
        "Beer": ["beer"],
        "Beer > Ale": ["ale"],
        "Beer > Ale > IPA": ["hop", "ipa", "pale ale", "xpa"],
        "Beer > Ale > Pale Ale": ["hop", "ipa", "pale", "pale ale", "xpa"],
        "Beer > Ale > Stout": ["ale", "stout"],
        "Beer > Craft Beer": ["craft", "craft beer"],
        "Beer > Craft Beer > Sour Beer": ["sour", "sour beer"],
        "Beer > Craft Beer > Wheat Beer": ["wheat", "wheat beer"],
        "Beer > Lager": ["budweiser", "carlsberg", "corona", "heineken", "lager", "stella"],
        "Beer > Lager > American Lager": ["american lager", "budweiser", "carlsberg", "corona", "heineken", "lager", "stella"],
        "Beer > Lager > Pilsner": ["budweiser", "carlsberg", "corona", "heineken", "pilsner", "stella"],
        "Liqueurs & Cordials": ["& cordials", "cordials", "liqueurs", "liqueurs &", "liqueurs & cordials"],
        "Liqueurs & Cordials > Cream Liqueurs": ["cream", "cream liqueurs", "liqueurs"],
        "Liqueurs & Cordials > Cream Liqueurs > Irish Cream": ["cream", "irish cream"],
        "Liqueurs & Cordials > Fruit Liqueurs": ["fruit", "fruit liqueurs", "liqueurs"],
        "Liqueurs & Cordials > Fruit Liqueurs > Berry Liqueurs": ["berry", "berry liqueurs", "liqueurs"],
        "Liqueurs & Cordials > Herbal Liqueurs": ["herbal", "herbal liqueurs", "liqueurs"],
        "Liqueurs & Cordials > Herbal Liqueurs > Digestif Bitters": ["bitters", "digestif", "digestif bitters"],
        "Spirits": ["spirits"],
        "Spirits > Brandy & Cognac": ["& cognac", "brandy &", "brandy & cognac"],
        "Spirits > Brandy & Cognac > Brandy": ["brandy"],
        "Spirits > Brandy & Cognac > Cognac": ["cognac"],
        "Spirits > Gin": ["bombay sapphire", "gin", "hendricks", "tanqueray"],
        "Spirits > Gin > Flavoured Gin": ["bombay sapphire", "flavoured gin", "hendricks", "tanqueray"],
        "Spirits > Gin > London Dry Gin": ["bombay sapphire", "dry gin", "hendricks", "london", "london dry", "london dry gin", "tanqueray"],
        "Spirits > Rum": ["bacardi", "captain morgan", "malibu", "rum"],
        "Spirits > Rum > Dark Rum": ["bacardi", "captain morgan", "dark", "dark rum", "malibu"],
        "Spirits > Rum > Spiced Rum": ["bacardi", "captain morgan", "malibu", "spiced", "spiced rum"],
        "Spirits > Rum > White Rum": ["bacardi", "captain morgan", "malibu", "white", "white rum"],
        "Spirits > Tequila": ["tequila"],
        "Spirits > Tequila > Blanco Tequila": ["blanco", "blanco tequila"],
        "Spirits > Tequila > Reposado Tequila": ["reposado", "reposado tequila"],
        "Spirits > Vodka": ["absolut", "grey goose", "smirnoff", "vodka"],
        "Spirits > Vodka > Flavoured Vodka": ["absolut", "flavoured vodka", "grey goose", "smirnoff"],
        "Spirits > Vodka > Premium Vodka": ["absolut", "grey goose", "premium vodka", "smirnoff"],
        "Spirits > Whisky": ["chivas", "glenfiddich", "jameson", "johnnie walker", "whisky"],
        "Spirits > Whisky > Bourbon": ["bourbon", "jack daniels", "jim beam", "makers mark", "wild turkey"],
        "Spirits > Whisky > Irish Whiskey": ["chivas", "glenfiddich", "irish whiskey", "jameson", "johnnie walker"],
        "Spirits > Whisky > Scotch": ["chivas", "glenfiddich", "jameson", "johnnie walker", "scotch"],
        "Wine": ["wine"],
        "Wine > Red Wine": ["cabernet", "merlot", "pinot noir", "red wine", "shiraz"],
        "Wine > Red Wine > Cabernet Sauvignon": ["cabernet", "cabernet sauvignon", "merlot", "pinot noir", "sauvignon", "shiraz"],
        "Wine > Red Wine > Merlot": ["cabernet", "merlot", "pinot noir", "shiraz"],
        "Wine > Red Wine > Pinot Noir": ["cabernet", "merlot", "noir", "pinot", "pinot noir", "shiraz"],
        "Wine > Rosé Wine": ["ros wine"],
        "Wine > Rosé Wine > Provence Rosé": ["provence", "provence ros"],
        "Wine > Sparkling Wine": ["sparkling", "sparkling wine"],
        "Wine > Sparkling Wine > Cava": ["cava"],
        "Wine > Sparkling Wine > Champagne": ["champagne"],
        "Wine > Sparkling Wine > Prosecco": ["prosecco"],
        "Wine > White Wine": ["chardonnay", "pinot gris", "riesling", "sauvignon blanc", "white", "white wine"],
        "Wine > White Wine > Chardonnay": ["chardonnay", "pinot gris", "riesling", "sauvignon blanc"],
        "Wine > White Wine > Riesling": ["chardonnay", "pinot gris", "riesling", "sauvignon blanc"],
        "Wine > White Wine > Sauvignon Blanc": ["blanc", "chardonnay", "pinot gris", "riesling", "sauvignon", "sauvignon blanc"],
    },
    "Baby & Toddler": {
        "Baby Clothing": ["baby clothing"],
        "Baby Clothing > Baby Outerwear": ["baby outerwear", "outerwear"],
        "Baby Clothing > Baby Outerwear > Baby Coats": ["baby coats", "coats"],
        "Baby Clothing > Baby Outerwear > Snowsuits": ["snowsuits"],
        "Baby Clothing > Baby Shoes": ["baby shoes", "shoes"],
        "Baby Clothing > Baby Shoes > Pre-Walker Shoes": ["pre-walker", "pre-walker shoes", "shoes"],
        "Baby Clothing > Babygrows": ["babygrows"],
        "Baby Clothing > Babygrows > Sleepsuits": ["sleepsuits"],
        "Baby Safety": ["baby safety", "safety"],
        "Baby Safety > Baby Gates": ["baby gates", "gates"],
        "Baby Safety > Baby Gates > Pressure-Fit Gates": ["gates", "pressure-fit", "pressure-fit gates"],
        "Baby Safety > Baby Gates > Stair Gates": ["gates", "stair", "stair gates"],
        "Baby Safety > Baby Monitors": ["baby monitors", "monitors"],
        "Baby Safety > Baby Monitors > Audio Monitors": ["audio", "audio monitors", "monitors"],
        "Baby Safety > Baby Monitors > Video Monitors": ["monitors", "video", "video monitors"],
        "Baby Safety > Corner Protectors": ["corner", "corner protectors", "protectors"],
        "Baby Safety > Corner Protectors > Furniture Guards": ["furniture guards", "guards"],
        "Feeding": ["anti-colic", "baby formula", "bottle", "bottles", "feeding", "formula", "sippy cup"],
        "Feeding > Baby Bottles": ["anti-colic", "baby bottles", "baby formula", "bottle", "bottles", "feeding", "formula", "sippy cup"],
        "Feeding > Baby Bottles > Anti-Colic Bottles": ["anti-colic", "anti-colic bottles", "baby formula", "bottle", "bottles", "feeding", "formula", "sippy cup"],
        "Feeding > Baby Bottles > Glass Bottles": ["anti-colic", "baby formula", "bottle", "bottles", "feeding", "formula", "glass", "glass bottles", "sippy cup"],
        "Feeding > Breastfeeding": ["anti-colic", "baby formula", "bottle", "bottles", "breastfeeding", "feeding", "formula", "sippy cup"],
        "Feeding > Breastfeeding > Breast Pumps": ["anti-colic", "baby formula", "bottle", "bottles", "breast", "breast pumps", "feeding", "formula", "pumps", "sippy cup"],
        "Feeding > Breastfeeding > Nursing Pillows": ["anti-colic", "baby formula", "bottle", "bottles", "feeding", "formula", "nursing", "nursing pillows", "pillows", "sippy cup"],
        "Feeding > Highchairs": ["anti-colic", "baby formula", "bottle", "bottles", "feeding", "formula", "highchairs", "sippy cup"],
        "Feeding > Highchairs > Convertible Highchairs": ["anti-colic", "baby formula", "bottle", "bottles", "convertible", "convertible highchairs", "feeding", "formula", "highchairs", "sippy cup"],
        "Feeding > Highchairs > Portable Highchairs": ["anti-colic", "baby formula", "bottle", "bottles", "feeding", "formula", "highchairs", "portable", "portable highchairs", "sippy cup"],
        "Feeding > Weaning": ["baby food", "baby formula", "formula", "infant formula", "milk powder", "powder", "puree", "weaning"],
        "Feeding > Weaning > Baby Spoons": ["baby food", "baby formula", "baby spoons", "formula", "infant formula", "milk powder", "powder", "puree", "spoons", "weaning"],
        "Feeding > Weaning > Sippy Cups": ["baby food", "baby formula", "cups", "formula", "infant formula", "milk powder", "powder", "puree", "sippy", "sippy cups", "weaning"],
        "Nappies & Changing": ["& changing", "baby dry", "changing", "diaper", "diapers", "huggies", "nappies", "nappies &", "nappies & changing", "nappy", "newborn", "pampers", "pull-up"],
        "Nappies & Changing > Changing Mats": ["baby dry", "changing", "changing mats", "diaper", "diapers", "huggies", "mats", "nappies", "nappy", "newborn", "pampers", "pull-up"],
        "Nappies & Changing > Changing Mats > Travel Changing Mats": ["baby dry", "changing", "changing mats", "diaper", "diapers", "huggies", "mats", "nappies", "nappy", "newborn", "pampers", "pull-up", "travel", "travel changing", "travel changing mats"],
        "Nappies & Changing > Disposable Nappies": ["baby dry", "diaper", "diapers", "disposable", "disposable nappies", "huggies", "nappies", "nappy", "newborn", "pampers", "pull-up"],
        "Nappies & Changing > Disposable Nappies > Newborn Nappies": ["baby dry", "diaper", "diapers", "huggies", "nappies", "nappy", "newborn", "newborn nappies", "pampers", "pull-up"],
        "Nappies & Changing > Disposable Nappies > Pull-Up Nappies": ["baby dry", "diaper", "diapers", "huggies", "nappies", "nappy", "newborn", "pampers", "pull-up", "pull-up nappies"],
        "Nappies & Changing > Nappy Bags": ["baby dry", "diaper", "diapers", "huggies", "nappies", "nappy", "nappy bags", "newborn", "pampers", "pull-up"],
        "Nappies & Changing > Nappy Bags > Nappy Disposal Bins": ["baby dry", "bins", "diaper", "diapers", "disposal", "disposal bins", "huggies", "nappies", "nappy", "nappy disposal", "nappy disposal bins", "newborn", "pampers", "pull-up"],
        "Nappies & Changing > Reusable Nappies": ["baby dry", "diaper", "diapers", "huggies", "nappies", "nappy", "newborn", "pampers", "pull-up", "reusable", "reusable nappies"],
        "Nappies & Changing > Reusable Nappies > Cloth Nappies": ["baby dry", "cloth", "cloth nappies", "diaper", "diapers", "huggies", "nappies", "nappy", "newborn", "pampers", "pull-up"],
        "Nursery Furniture": ["nursery", "nursery furniture"],
        "Nursery Furniture > Cots & Cribs": ["& cribs", "cots", "cots &", "cots & cribs", "cribs"],
        "Nursery Furniture > Cots & Cribs > Convertible Cots": ["convertible", "convertible cots", "cots"],
        "Nursery Furniture > Cots & Cribs > Travel Cots": ["cots", "travel", "travel cots"],
        "Nursery Furniture > Nursery Storage": ["nursery", "nursery storage", "storage"],
        "Nursery Furniture > Nursery Storage > Changing Tables": ["changing", "changing tables", "tables"],
        "Nursery Furniture > Nursery Storage > Toy Storage": ["storage", "toy storage"],
        "Nursery Furniture > Rocking Chairs": ["chairs", "rocking", "rocking chairs"],
        "Nursery Furniture > Rocking Chairs > Nursing Chairs": ["chairs", "nursing", "nursing chairs"],
        "Travel": ["travel"],
        "Travel > Baby Carriers": ["baby carrier", "baby carriers", "baby sling", "carrier", "carriers", "sling", "structured carrier", "wrap"],
        "Travel > Baby Carriers > Baby Slings": ["baby carrier", "baby sling", "baby slings", "carrier", "sling", "slings", "structured carrier", "wrap"],
        "Travel > Baby Carriers > Structured Carriers": ["baby carrier", "baby sling", "carrier", "carriers", "sling", "structured", "structured carrier", "structured carriers", "wrap"],
        "Travel > Car Seats": ["car seat", "car seats", "carseat", "convertible car seat", "infant seat", "isofix", "safety seat", "seats"],
        "Travel > Car Seats > Convertible Car Seats": ["car seat", "car seats", "carseat", "convertible", "convertible car", "convertible car seat", "convertible car seats", "infant seat", "isofix", "safety seat", "seats"],
        "Travel > Car Seats > Infant Car Seats": ["car seat", "car seats", "carseat", "convertible car seat", "infant car", "infant car seats", "infant seat", "isofix", "safety seat", "seats"],
        "Travel > Pushchairs": ["buggy", "compact", "lightweight", "pram", "prams", "pushchair", "pushchairs", "stroller", "strollers", "travel system"],
        "Travel > Pushchairs > Double Pushchairs": ["buggy", "compact", "double", "double pushchairs", "lightweight", "pram", "prams", "pushchair", "pushchairs", "stroller", "strollers", "travel system"],
        "Travel > Pushchairs > Single Pushchairs": ["buggy", "compact", "lightweight", "pram", "prams", "pushchair", "pushchairs", "single", "single pushchairs", "stroller", "strollers", "travel system"],
        "Travel > Pushchairs > Travel Systems": ["buggy", "compact", "lightweight", "pram", "prams", "pushchair", "stroller", "strollers", "systems", "travel", "travel system", "travel systems"],
    },
    "Cameras & Optics": {
        "Camera Accessories": ["camera accessories"],
        "Camera Accessories > Camera Bags": ["camera bag", "camera bags", "case"],
        "Camera Accessories > Camera Bags > Backpack Cases": ["backpack", "backpack cases", "camera bag", "case", "cases"],
        "Camera Accessories > Camera Bags > Shoulder Bags": ["camera bag", "case", "shoulder", "shoulder bags"],
        "Camera Accessories > Filters": ["52mm", "67mm", "77mm", "82mm", "cpl", "filter", "filters", "lens filter", "nd filter", "polarizer", "uv filter"],
        "Camera Accessories > Filters > ND Filters": ["52mm", "67mm", "77mm", "82mm", "cpl", "filter", "filters", "lens filter", "nd filter", "nd filters", "polarizer", "uv filter"],
        "Camera Accessories > Filters > UV Filters": ["52mm", "67mm", "77mm", "82mm", "cpl", "filter", "filters", "lens filter", "nd filter", "polarizer", "uv filter", "uv filters"],
        "Camera Accessories > Flash Units": ["flash", "flash units", "units"],
        "Camera Accessories > Flash Units > External Flash": ["external", "external flash", "flash"],
        "Camera Accessories > Flash Units > Studio Lighting": ["lighting", "studio", "studio lighting"],
        "Camera Accessories > Memory Cards": ["cards", "memory", "memory cards"],
        "Camera Accessories > Memory Cards > CF Cards": ["cards", "cf cards"],
        "Camera Accessories > Memory Cards > SD Cards": ["cards", "sd cards"],
        "Camera Accessories > Tripods & Supports": ["& supports", "mount", "stand", "supports", "tripod", "tripods", "tripods &", "tripods & supports"],
        "Camera Accessories > Tripods & Supports > Gimbals": ["gimbals", "mount", "stand", "tripod"],
        "Camera Accessories > Tripods & Supports > Monopods": ["monopods", "mount", "stand", "tripod"],
        "Camera Accessories > Tripods & Supports > Tripods": ["mount", "stand", "tripod", "tripods"],
        "Camera Lenses": ["camera lenses", "lens", "lenses", "mm", "prime", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Prime Lenses": ["lens", "lenses", "mm", "prime", "prime lenses", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Prime Lenses > Portrait Lenses": ["lens", "lenses", "mm", "portrait", "portrait lenses", "prime", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Prime Lenses > Wide Angle Lenses": ["angle", "angle lenses", "lens", "lenses", "mm", "prime", "telephoto", "wide", "wide angle", "wide angle lenses", "zoom"],
        "Camera Lenses > Specialty Lenses": ["lens", "lenses", "mm", "prime", "specialty", "specialty lenses", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Specialty Lenses > Fisheye Lenses": ["fisheye", "fisheye lenses", "lens", "lenses", "mm", "prime", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Specialty Lenses > Macro Lenses": ["lens", "lenses", "macro", "macro lenses", "mm", "prime", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Zoom Lenses": ["lens", "lenses", "mm", "prime", "telephoto", "wide angle", "zoom", "zoom lenses"],
        "Camera Lenses > Zoom Lenses > Standard Zoom": ["lens", "lenses", "mm", "prime", "standard zoom", "telephoto", "wide angle", "zoom"],
        "Camera Lenses > Zoom Lenses > Telephoto Lenses": ["lens", "lenses", "mm", "prime", "telephoto", "telephoto lenses", "wide angle", "zoom"],
        "Cameras": ["cameras", "canon", "fujifilm", "nikon", "olympus", "panasonic", "sony"],
        "Cameras > Action Cameras": ["action", "action cameras", "cameras"],
        "Cameras > Action Cameras > Sports Cameras": ["cameras", "sports", "sports cameras"],
        "Cameras > Action Cameras > Waterproof Cameras": ["cameras", "waterproof", "waterproof cameras"],
        "Cameras > Digital Cameras": ["cameras", "digital", "digital cameras"],
        "Cameras > Digital Cameras > Compact Cameras": ["cameras", "compact", "compact cameras"],
        "Cameras > Digital Cameras > DSLR Cameras": ["cameras", "dslr", "dslr cameras"],
        "Cameras > Digital Cameras > Mirrorless Cameras": ["cameras", "mirrorless", "mirrorless cameras"],
        "Cameras > Film Cameras": ["cameras", "film", "film cameras"],
        "Cameras > Film Cameras > 35mm Cameras": ["35mm", "35mm cameras", "cameras"],
        "Cameras > Film Cameras > Instant Cameras": ["cameras", "instant", "instant cameras"],
        "Cameras > Video Cameras": ["cameras", "video", "video cameras"],
        "Cameras > Video Cameras > Camcorders": ["camcorders"],
        "Cameras > Video Cameras > Professional Video": ["professional", "professional video", "video"],
        "Drones": ["drones"],
        "Drones > Consumer Drones": ["consumer", "consumer drones", "drones"],
        "Drones > Consumer Drones > Camera Drones": ["camera drones", "drones"],
        "Drones > Consumer Drones > Racing Drones": ["drones", "racing", "racing drones"],
        "Drones > Drone Accessories": ["drone", "drone accessories"],
        "Drones > Drone Accessories > Drone Batteries": ["batteries", "drone", "drone batteries"],
        "Drones > Drone Accessories > Propellers": ["propellers"],
        "Optics": ["optics"],
        "Optics > Binoculars": ["binocular", "binoculars", "optics"],
        "Optics > Binoculars > Compact Binoculars": ["binocular", "binoculars", "compact", "compact binoculars", "optics"],
        "Optics > Binoculars > Full-Size Binoculars": ["binocular", "binoculars", "full-size", "full-size binoculars", "optics"],
        "Optics > Monoculars": ["monoculars"],
        "Optics > Monoculars > Compact Monoculars": ["compact", "compact monoculars", "monoculars"],
        "Optics > Spotting Scopes": ["scopes", "spotting", "spotting scopes"],
        "Optics > Spotting Scopes > Birdwatching Scopes": ["birdwatching", "birdwatching scopes", "scopes"],
        "Optics > Telescopes": ["telescopes"],
        "Optics > Telescopes > Reflector Telescopes": ["reflector", "reflector telescopes", "telescopes"],
        "Optics > Telescopes > Refractor Telescopes": ["refractor", "refractor telescopes", "telescopes"],
    },
    "Electronics": {
        "Audio": ["audio"],
        "Audio > Headphones & Earphones": ["& earphones", "earphones", "headphones", "headphones &", "headphones & earphones"],
        "Audio > Headphones & Earphones > In-Ear Headphones": ["headphones", "in-ear", "in-ear headphones"],
        "Audio > Headphones & Earphones > Over-Ear Headphones": ["headphones", "over-ear", "over-ear headphones"],
        "Audio > Headphones & Earphones > Wireless Headphones": ["headphones", "wireless", "wireless headphones"],
        "Audio > Home Audio": ["audio", "home", "home audio"],
        "Audio > Home Audio > Amplifiers & Receivers": ["& receivers", "amplifiers", "amplifiers &", "amplifiers & receivers", "receivers"],
        "Audio > Home Audio > Turntables": ["turntables"],
        "Audio > MP3 Players": ["mp3 players", "players"],
        "Audio > MP3 Players > Portable Media Players": ["media", "media players", "players", "portable", "portable media", "portable media players"],
        "Audio > Speakers": ["speakers"],
        "Audio > Speakers > Bluetooth Speakers": ["bluetooth", "bluetooth speakers", "speakers"],
        "Audio > Speakers > Home Speakers": ["home", "home speakers", "speakers"],
        "Audio > Speakers > Soundbars": ["soundbars"],
        "Communications": ["communications"],
        "Communications > Landline Phones": ["landline", "landline phones", "phones"],
        "Communications > Landline Phones > Cordless Phones": ["cordless", "cordless phones", "phones"],
        "Communications > Mobile Phone Accessories": ["mobile", "mobile phone", "mobile phone accessories", "phone", "phone accessories"],
        "Communications > Mobile Phone Accessories > Chargers & Cables": ["& cables", "cable", "cables", "charger", "chargers", "chargers &", "chargers & cables", "usb-c cable"],
        "Communications > Mobile Phone Accessories > Phone Cases": ["case", "cases", "cover", "covers", "phone", "phone case", "phone cases"],
        "Communications > Mobile Phone Accessories > Screen Protectors": ["protector", "protectors", "screen", "screen protector", "screen protectors", "tempered glass"],
        "Communications > Mobile Phones": ["mobile", "mobile phones", "phones"],
        "Communications > Mobile Phones > Feature Phones": ["feature", "feature phones", "phones"],
        "Communications > Mobile Phones > Smartphones": ["5g phone", "galaxy a", "galaxy s", "galaxy s23", "galaxy s24", "galaxy s25", "galaxy z", "iphone", "mobile phone", "motorola", "nokia", "oneplus", "oppo", "pixel", "pixel 9", "realme", "samsung galaxy", "smartphone", "smartphones", "vivo"],
        "Computers": ["computers"],
        "Computers > Computer Components": ["components", "computer", "computer components"],
        "Computers > Computer Components > Graphics Cards": ["cards", "graphics", "graphics cards"],
        "Computers > Computer Components > Hard Drives & SSDs": ["& ssds", "drives", "drives &", "hard", "hard drives", "hard drives & ssds", "ssds"],
        "Computers > Computer Components > RAM Memory": ["memory", "ram memory"],
        "Computers > Desktop Computers": ["computers", "desktop", "desktop computers"],
        "Computers > Desktop Computers > All-in-One PCs": ["all-in-one", "all-in-one pcs"],
        "Computers > Desktop Computers > Gaming PCs": ["gaming", "gaming pcs"],
        "Computers > Laptops": ["asus", "dell", "hp", "laptops", "lenovo", "macbook", "thinkpad"],
        "Computers > Laptops > Business Laptops": ["asus", "business", "business laptops", "dell", "hp", "laptops", "lenovo", "macbook", "thinkpad"],
        "Computers > Laptops > Gaming Laptops": ["asus", "dell", "gaming", "gaming laptops", "hp", "laptops", "lenovo", "macbook", "thinkpad"],
        "Computers > Tablets": ["galaxy tab", "ipad", "surface", "tablets"],
        "Computers > Tablets > Android Tablets": ["android", "android tablets", "galaxy tab", "ipad", "surface", "tablets"],
        "Computers > Tablets > iPads": ["galaxy tab", "ipad", "ipads", "surface"],
        "Gaming": ["gaming"],
        "Gaming > Gaming Controllers": ["controller", "controllers", "dualsense", "dualshock", "gamepad", "gamepads", "gaming", "gaming controllers", "joystick", "joysticks"],
        "Gaming > Gaming Controllers > Gamepads": ["controller", "controllers", "dualsense", "dualshock", "gamepad", "gamepads", "joystick", "joysticks"],
        "Gaming > Gaming Controllers > Joysticks": ["controller", "controllers", "dualsense", "dualshock", "gamepad", "gamepads", "joystick", "joysticks"],
        "Gaming > Video Game Consoles": ["consoles", "game", "game consoles", "nintendo", "playstation", "ps4", "ps5", "ps6", "switch", "video", "video game", "video game consoles", "xbox"],
        "Gaming > Video Game Consoles > Handheld Consoles": ["consoles", "handheld", "handheld consoles", "nintendo", "playstation", "ps4", "ps5", "ps6", "switch", "xbox"],
        "Gaming > Video Game Consoles > Home Consoles": ["consoles", "home", "home consoles", "nintendo", "playstation", "ps4", "ps5", "ps6", "switch", "xbox"],
        "Gaming > Video Games": ["games", "video", "video games"],
        "Gaming > Video Games > Console Games": ["console", "console games", "games"],
        "Gaming > Video Games > PC Games": ["games", "pc games"],
        "Home Appliances": ["appliances", "home", "home appliances"],
        "Home Appliances > Climate Control": ["climate", "climate control", "control"],
        "Home Appliances > Climate Control > Air Conditioners": ["air conditioners", "conditioners"],
        "Home Appliances > Climate Control > Heaters": ["heaters"],
        "Home Appliances > Kitchen Appliances": ["appliances", "kitchen", "kitchen appliances"],
        "Home Appliances > Kitchen Appliances > Blenders": ["blenders"],
        "Home Appliances > Kitchen Appliances > Coffee Makers": ["coffee", "coffee makers", "makers"],
        "Home Appliances > Kitchen Appliances > Microwaves": ["microwaves"],
        "Home Appliances > Vacuum Cleaners": ["cleaners", "vacuum", "vacuum cleaners"],
        "Home Appliances > Vacuum Cleaners > Cordless Vacuums": ["cordless", "cordless vacuums", "vacuums"],
        "Home Appliances > Vacuum Cleaners > Robot Vacuums": ["robot", "robot vacuums", "vacuums"],
        "Video": ["video"],
        "Video > DVD & Blu-ray Players": ["& blu-ray", "blu-ray", "blu-ray players", "dvd &", "dvd & blu-ray players", "players"],
        "Video > DVD & Blu-ray Players > Blu-ray Players": ["blu-ray", "blu-ray players", "players"],
        "Video > Projectors": ["projectors"],
        "Video > Projectors > Home Projectors": ["home", "home projectors", "projectors"],
        "Video > Projectors > Portable Projectors": ["portable", "portable projectors", "projectors"],
        "Video > Streaming Devices": ["devices", "streaming", "streaming devices"],
        "Video > Streaming Devices > Media Streaming Sticks": ["media", "media streaming", "media streaming sticks", "sticks", "streaming", "streaming sticks"],
        "Video > Televisions": ["55 inch", "65 inch", "75 inch", "inch tv", "led tv", "oled", "qled", "smart tv", "television", "televisions", "tv"],
        "Video > Televisions > LED TVs": ["55 inch", "65 inch", "75 inch", "inch tv", "led tv", "led tvs", "oled", "qled", "smart tv", "television", "tv"],
        "Video > Televisions > OLED TVs": ["55 inch", "65 inch", "75 inch", "inch tv", "led tv", "oled", "oled tvs", "qled", "smart tv", "television", "tv"],
        "Video > Televisions > Smart TVs": ["55 inch", "65 inch", "75 inch", "inch tv", "led tv", "oled", "qled", "smart", "smart tv", "smart tvs", "television", "tv"],
        "Wearables": ["wearables"],
        "Wearables > Fitness Trackers": ["fitness", "fitness trackers", "trackers"],
        "Wearables > Fitness Trackers > Activity Bands": ["activity", "activity bands", "bands"],
        "Wearables > Smartwatches": ["smartwatches"],
        "Wearables > Smartwatches > Fitness Smartwatches": ["fitness", "fitness smartwatches", "smartwatches"],
        "Wearables > Smartwatches > Luxury Smartwatches": ["luxury", "luxury smartwatches", "smartwatches"],
        "Wearables > VR Headsets": ["headsets", "vr headsets"],
        "Wearables > VR Headsets > Standalone VR": ["standalone", "standalone vr"],
    },
    "F&F (Later)": {
        "Clothing & Accessories": ["& accessories", "clothing &", "clothing & accessories"],
        "Clothing & Accessories > Clothing": ["clothing"],
        "Clothing & Accessories > Clothing > Activewear": ["activewear"],
    },
    "Furniture": {
        "Bedroom Furniture": ["bedroom", "bedroom furniture"],
        "Bedroom Furniture > Beds": ["bed", "beds", "double", "king", "queen", "single"],
        "Bedroom Furniture > Beds > Bunk Beds": ["bed", "beds", "bunk", "bunk beds", "double", "king", "queen", "single"],
        "Bedroom Furniture > Beds > Double Beds": ["bed", "beds", "double", "double beds", "king", "queen", "single"],
        "Bedroom Furniture > Beds > King Size Beds": ["bed", "beds", "double", "king", "king size", "king size beds", "queen", "single", "size", "size beds"],
        "Bedroom Furniture > Beds > Single Beds": ["bed", "beds", "double", "king", "queen", "single", "single beds"],
        "Bedroom Furniture > Bedside Tables": ["bed", "bedside", "bedside tables", "double", "king", "queen", "single", "tables"],
        "Bedroom Furniture > Bedside Tables > Nightstands": ["bed", "double", "king", "nightstands", "queen", "single"],
        "Bedroom Furniture > Mattresses": ["mattress", "mattresses", "memory foam", "spring"],
        "Bedroom Furniture > Mattresses > Memory Foam Mattresses": ["foam", "foam mattresses", "mattress", "mattresses", "memory", "memory foam", "memory foam mattresses", "spring"],
        "Bedroom Furniture > Mattresses > Pocket Sprung Mattresses": ["mattress", "mattresses", "memory foam", "pocket", "pocket sprung", "pocket sprung mattresses", "spring", "sprung", "sprung mattresses"],
        "Bedroom Furniture > Storage": ["storage"],
        "Bedroom Furniture > Storage > Chests of Drawers": ["chests", "chests of", "chests of drawers", "drawers", "of drawers"],
        "Bedroom Furniture > Storage > Wardrobes": ["wardrobes"],
        "Children's Furniture": ["childrens", "childrens furniture"],
        "Children's Furniture > Children's Beds": ["bed", "beds", "childrens", "childrens beds", "double", "king", "queen", "single"],
        "Children's Furniture > Children's Beds > Mid Sleeper Beds": ["bed", "beds", "double", "king", "mid sleeper", "mid sleeper beds", "queen", "single", "sleeper", "sleeper beds"],
        "Children's Furniture > Children's Beds > Toddler Beds": ["bed", "beds", "double", "king", "queen", "single", "toddler beds"],
        "Children's Furniture > Children's Desks": ["childrens", "childrens desks", "desks"],
        "Children's Furniture > Children's Desks > Study Desks": ["desks", "study", "study desks"],
        "Children's Furniture > Children's Storage": ["childrens", "childrens storage", "storage"],
        "Children's Furniture > Children's Storage > Toy Boxes": ["boxes", "toy boxes"],
        "Dining Room Furniture": ["dining", "dining room", "dining room furniture", "room", "room furniture"],
        "Dining Room Furniture > Dining Chairs": ["chair", "chairs", "dining", "dining chairs", "seating"],
        "Dining Room Furniture > Dining Chairs > Upholstered Chairs": ["chair", "chairs", "seating", "upholstered", "upholstered chairs"],
        "Dining Room Furniture > Dining Chairs > Wooden Chairs": ["chair", "chairs", "seating", "wooden", "wooden chairs"],
        "Dining Room Furniture > Dining Tables": ["dining", "dining table", "dining tables", "table", "tables"],
        "Dining Room Furniture > Dining Tables > Extendable Tables": ["dining table", "extendable", "extendable tables", "table", "tables"],
        "Dining Room Furniture > Dining Tables > Round Tables": ["dining table", "round", "round tables", "table", "tables"],
        "Dining Room Furniture > Storage": ["storage"],
        "Dining Room Furniture > Storage > Display Cabinets": ["cabinets", "display", "display cabinets"],
        "Dining Room Furniture > Storage > Sideboards": ["sideboards"],
        "Kitchen Furniture": ["kitchen", "kitchen furniture"],
        "Kitchen Furniture > Kitchen Chairs": ["chair", "chairs", "kitchen", "kitchen chairs", "seating"],
        "Kitchen Furniture > Kitchen Chairs > Bar Stools": ["bar stools", "chair", "seating", "stools"],
        "Kitchen Furniture > Kitchen Storage": ["kitchen", "kitchen storage", "storage"],
        "Kitchen Furniture > Kitchen Storage > Kitchen Islands": ["islands", "kitchen", "kitchen islands"],
        "Kitchen Furniture > Kitchen Storage > Kitchen Trolleys": ["kitchen", "kitchen trolleys", "trolleys"],
        "Kitchen Furniture > Kitchen Tables": ["kitchen", "kitchen tables", "tables"],
        "Kitchen Furniture > Kitchen Tables > Breakfast Tables": ["breakfast", "breakfast tables", "tables"],
        "Living Room Furniture": ["living", "living room", "living room furniture", "room", "room furniture"],
        "Living Room Furniture > Chairs": ["chair", "chairs", "seating"],
        "Living Room Furniture > Chairs > Accent Chairs": ["accent", "accent chairs", "chair", "chairs", "seating"],
        "Living Room Furniture > Chairs > Armchairs": ["armchairs", "chair", "seating"],
        "Living Room Furniture > Sofas": ["couch", "sectional", "sofa", "sofas"],
        "Living Room Furniture > Sofas > Corner Sofas": ["corner", "corner sofas", "couch", "sectional", "sofa", "sofas"],
        "Living Room Furniture > Sofas > Recliners": ["couch", "recliners", "sectional", "sofa"],
        "Living Room Furniture > Sofas > Sofa Beds": ["bed", "beds", "double", "king", "queen", "single", "sofa", "sofa beds"],
        "Living Room Furniture > TV & Media Units": ["& media", "media", "media units", "tv &", "tv & media units", "units"],
        "Living Room Furniture > TV & Media Units > Entertainment Centres": ["centres", "entertainment", "entertainment centres"],
        "Living Room Furniture > TV & Media Units > TV Cabinets": ["cabinets", "tv cabinets"],
        "Living Room Furniture > Tables": ["tables"],
        "Living Room Furniture > Tables > Coffee Tables": ["coffee", "coffee table", "coffee tables", "table", "tables"],
        "Living Room Furniture > Tables > Side Tables": ["side", "side tables", "tables"],
        "Office Furniture": ["office", "office furniture"],
        "Office Furniture > Desks": ["desks"],
        "Office Furniture > Desks > Computer Desks": ["computer", "computer desks", "desks"],
        "Office Furniture > Desks > Corner Desks": ["corner", "corner desks", "desks"],
        "Office Furniture > Desks > Standing Desks": ["desks", "standing", "standing desks"],
        "Office Furniture > Office Chairs": ["chair", "chairs", "office", "office chairs", "seating"],
        "Office Furniture > Office Chairs > Ergonomic Chairs": ["chair", "chairs", "ergonomic", "ergonomic chairs", "seating"],
        "Office Furniture > Office Chairs > Executive Chairs": ["chair", "chairs", "executive", "executive chairs", "seating"],
        "Office Furniture > Storage": ["storage"],
        "Office Furniture > Storage > Bookcases": ["bookcases"],
        "Office Furniture > Storage > Filing Cabinets": ["cabinets", "filing", "filing cabinets"],
        "Outdoor Furniture": ["outdoor", "outdoor furniture"],
        "Outdoor Furniture > Garden Seating": ["garden", "garden seating", "seating"],
        "Outdoor Furniture > Garden Seating > Garden Benches": ["benches", "garden", "garden benches"],
        "Outdoor Furniture > Garden Seating > Garden Sofas": ["couch", "garden", "garden sofas", "sectional", "sofa", "sofas"],
        "Outdoor Furniture > Garden Tables": ["garden", "garden tables", "tables"],
        "Outdoor Furniture > Garden Tables > Bistro Sets": ["bistro", "bistro sets", "sets"],
        "Outdoor Furniture > Garden Tables > Patio Tables": ["patio", "patio tables", "tables"],
        "Outdoor Furniture > Sun Loungers": ["loungers", "sun loungers"],
        "Outdoor Furniture > Sun Loungers > Reclining Loungers": ["loungers", "reclining", "reclining loungers"],
    },
    "Hardware": {
        "Building Materials": ["building", "building materials", "materials"],
        "Building Materials > Concrete & Cement": ["& cement", "cement", "concrete", "concrete &", "concrete & cement"],
        "Building Materials > Concrete & Cement > Mortar": ["mortar"],
        "Building Materials > Concrete & Cement > Ready Mix": ["ready", "ready mix"],
        "Building Materials > Insulation": ["insulation"],
        "Building Materials > Insulation > Fibreglass Insulation": ["fibreglass", "fibreglass insulation", "insulation"],
        "Building Materials > Insulation > Foam Board": ["board", "foam", "foam board"],
        "Building Materials > Lumber": ["lumber"],
        "Building Materials > Lumber > Plywood": ["plywood"],
        "Building Materials > Lumber > Timber": ["timber"],
        "Electrical": ["electrical"],
        "Electrical > Lighting": ["lighting"],
        "Electrical > Lighting > Fluorescent Tubes": ["fluorescent", "fluorescent tubes", "tubes"],
        "Electrical > Lighting > LED Bulbs": ["bulbs", "led bulbs"],
        "Electrical > Switches & Sockets": ["& sockets", "sockets", "switches", "switches &", "switches & sockets"],
        "Electrical > Switches & Sockets > Light Switches": ["light", "light switches", "switches"],
        "Electrical > Switches & Sockets > Power Sockets": ["power", "power sockets", "sockets"],
        "Electrical > Wiring": ["wiring"],
        "Electrical > Wiring > Electrical Cable": ["cable", "electrical", "electrical cable"],
        "Electrical > Wiring > Junction Boxes": ["boxes", "junction", "junction boxes"],
        "Fasteners": ["fasteners"],
        "Fasteners > Anchors": ["anchors"],
        "Fasteners > Anchors > Concrete Anchors": ["anchors", "concrete", "concrete anchors"],
        "Fasteners > Anchors > Wall Anchors": ["anchors", "wall", "wall anchors"],
        "Fasteners > Bolts & Nuts": ["& nuts", "bolts", "bolts &", "bolts & nuts", "nuts"],
        "Fasteners > Bolts & Nuts > Carriage Bolts": ["bolts", "carriage", "carriage bolts"],
        "Fasteners > Bolts & Nuts > Hex Bolts": ["bolts", "hex bolts"],
        "Fasteners > Nails": ["nails"],
        "Fasteners > Nails > Masonry Nails": ["masonry", "masonry nails", "nails"],
        "Fasteners > Nails > Wire Nails": ["nails", "wire", "wire nails"],
        "Fasteners > Screws": ["screws"],
        "Fasteners > Screws > Machine Screws": ["machine", "machine screws", "screws"],
        "Fasteners > Screws > Wood Screws": ["screws", "wood", "wood screws"],
        "Hand Tools": ["hand", "hand tools", "tools"],
        "Hand Tools > Hammers": ["hammer", "hammers", "mallet"],
        "Hand Tools > Hammers > Ball Peen Hammers": ["ball", "ball peen", "ball peen hammers", "hammer", "hammers", "mallet", "peen", "peen hammers"],
        "Hand Tools > Hammers > Claw Hammers": ["claw", "claw hammers", "hammer", "hammers", "mallet"],
        "Hand Tools > Measuring Tools": ["measuring", "measuring tools", "tools"],
        "Hand Tools > Measuring Tools > Spirit Levels": ["levels", "spirit", "spirit levels"],
        "Hand Tools > Measuring Tools > Tape Measures": ["measures", "tape", "tape measures"],
        "Hand Tools > Pliers": ["pliers"],
        "Hand Tools > Pliers > Combination Pliers": ["combination", "combination pliers", "pliers"],
        "Hand Tools > Pliers > Needle Nose Pliers": ["needle", "needle nose", "needle nose pliers", "nose", "nose pliers", "pliers"],
        "Hand Tools > Screwdrivers": ["flathead", "phillips", "screwdriver", "screwdrivers"],
        "Hand Tools > Screwdrivers > Flathead Screwdrivers": ["flathead", "flathead screwdrivers", "phillips", "screwdriver", "screwdrivers"],
        "Hand Tools > Screwdrivers > Phillips Screwdrivers": ["flathead", "phillips", "phillips screwdrivers", "screwdriver", "screwdrivers"],
        "Hand Tools > Screwdrivers > Screwdriver Sets": ["flathead", "phillips", "screwdriver", "screwdriver sets", "sets"],
        "Hand Tools > Wrenches": ["wrenches"],
        "Hand Tools > Wrenches > Adjustable Wrenches": ["adjustable", "adjustable wrenches", "wrenches"],
        "Hand Tools > Wrenches > Socket Sets": ["sets", "socket", "socket sets"],
        "Paint": ["crown", "dulux", "emulsion", "exterior paint", "gloss paint", "interior paint", "matt paint", "paint", "wall paint"],
        "Paint Brushes": ["brush", "brushes", "paint brush", "painting brush"],
        "Paint Rollers": ["paint roller", "roller", "rollers"],
        "Painting Tools": ["brush", "exterior paint", "interior paint", "paint", "paint brush", "paint roller", "painting", "primer", "roller", "spray paint", "wall paint"],
        "Plumbing": ["plumbing"],
        "Plumbing > Pipes & Fittings": ["& fittings", "fittings", "pipes", "pipes &", "pipes & fittings"],
        "Plumbing > Pipes & Fittings > Copper Pipes": ["copper", "copper pipes", "pipes"],
        "Plumbing > Pipes & Fittings > PVC Pipes": ["pipes", "pvc pipes"],
        "Plumbing > Taps & Mixers": ["& mixers", "mixers", "taps", "taps &", "taps & mixers"],
        "Plumbing > Taps & Mixers > Basin Taps": ["basin", "basin taps", "taps"],
        "Plumbing > Taps & Mixers > Kitchen Taps": ["kitchen", "kitchen taps", "taps"],
        "Plumbing > Valves": ["valves"],
        "Plumbing > Valves > Ball Valves": ["ball", "ball valves", "valves"],
        "Plumbing > Valves > Gate Valves": ["gate", "gate valves", "valves"],
        "Power Tools": ["power", "power tools", "tools"],
        "Power Tools > Drills": ["cordless", "drill", "drills", "driver"],
        "Power Tools > Drills > Cordless Drills": ["cordless", "cordless drills", "drill", "drills", "driver"],
        "Power Tools > Drills > Hammer Drills": ["cordless", "drill", "drills", "driver", "hammer", "hammer drills"],
        "Power Tools > Drills > Impact Drivers": ["cordless", "drill", "driver", "drivers", "impact", "impact drivers"],
        "Power Tools > Grinders": ["grinders"],
        "Power Tools > Grinders > Angle Grinders": ["angle", "angle grinders", "grinders"],
        "Power Tools > Grinders > Bench Grinders": ["bench", "bench grinders", "grinders"],
        "Power Tools > Sanders": ["sanders"],
        "Power Tools > Sanders > Belt Sanders": ["belt", "belt sanders", "sanders"],
        "Power Tools > Sanders > Orbital Sanders": ["orbital", "orbital sanders", "sanders"],
        "Power Tools > Saws": ["chainsaw", "circular saw", "saw", "saws"],
        "Power Tools > Saws > Circular Saws": ["chainsaw", "circular", "circular saw", "circular saws", "saw", "saws"],
        "Power Tools > Saws > Jigsaws": ["chainsaw", "circular saw", "jigsaws", "saw"],
        "Power Tools > Saws > Reciprocating Saws": ["chainsaw", "circular saw", "reciprocating", "reciprocating saws", "saw", "saws"],
        "Safety Equipment": ["equipment", "safety", "safety equipment"],
        "Safety Equipment > Protective Gear": ["gear", "protective", "protective gear"],
        "Safety Equipment > Protective Gear > Hard Hats": ["hard", "hard hats", "hats"],
        "Safety Equipment > Protective Gear > Safety Glasses": ["glasses", "safety", "safety glasses"],
        "Safety Equipment > Protective Gear > Work Gloves": ["gloves", "work", "work gloves"],
    },
    "Health & Beauty": {
        "Fragrances": ["fragrances"],
        "Fragrances > Men's Cologne": ["cologne", "eau de", "fragrance", "mens", "mens cologne", "perfume"],
        "Fragrances > Men's Cologne > Aftershave": ["aftershave", "cologne", "eau de", "fragrance", "perfume"],
        "Fragrances > Men's Cologne > Body Spray": ["body", "body spray", "cologne", "eau de", "fragrance", "perfume", "spray"],
        "Fragrances > Women's Perfume": ["cologne", "eau de", "fragrance", "perfume", "womens", "womens perfume"],
        "Fragrances > Women's Perfume > Eau de Parfum": ["cologne", "de parfum", "eau de", "eau de parfum", "fragrance", "parfum", "perfume"],
        "Fragrances > Women's Perfume > Eau de Toilette": ["cologne", "de toilette", "eau de", "eau de toilette", "fragrance", "perfume", "toilette"],
        "Haircare": ["haircare"],
        "Haircare > Conditioner": ["conditioner", "hair conditioner", "treatment"],
        "Haircare > Conditioner > Deep Conditioner": ["conditioner", "deep", "deep conditioner", "hair conditioner", "treatment"],
        "Haircare > Conditioner > Leave-In Conditioner": ["conditioner", "hair conditioner", "leave-in", "leave-in conditioner", "treatment"],
        "Haircare > Hair Colour": ["colour", "hair", "hair colour"],
        "Haircare > Hair Colour > Permanent Colour": ["colour", "permanent", "permanent colour"],
        "Haircare > Hair Colour > Semi-Permanent Colour": ["colour", "semi-permanent", "semi-permanent colour"],
        "Haircare > Hair Styling": ["hair", "hair styling", "styling"],
        "Haircare > Hair Styling > Hair Gel": ["hair", "hair gel"],
        "Haircare > Hair Styling > Hair Spray": ["hair", "hair spray", "spray"],
        "Haircare > Hair Tools": ["hair", "hair tools", "tools"],
        "Haircare > Hair Tools > Curling Irons": ["curling", "curling irons", "irons"],
        "Haircare > Hair Tools > Hair Dryers": ["dryers", "hair", "hair dryers"],
        "Haircare > Hair Tools > Straighteners": ["straighteners"],
        "Haircare > Shampoo": ["cleansing", "hair wash", "shampoo"],
        "Haircare > Shampoo > Clarifying Shampoo": ["clarifying", "clarifying shampoo", "cleansing", "hair wash", "shampoo"],
        "Haircare > Shampoo > Moisturising Shampoo": ["cleansing", "hair wash", "moisturising", "moisturising shampoo", "shampoo"],
        "Makeup": ["makeup"],
        "Makeup > Eye Makeup": ["eye makeup", "makeup"],
        "Makeup > Eye Makeup > Eyeliner": ["eyeliner"],
        "Makeup > Eye Makeup > Eyeshadow": ["eyeshadow"],
        "Makeup > Eye Makeup > Mascara": ["mascara"],
        "Makeup > Face Makeup": ["face", "face makeup", "makeup"],
        "Makeup > Face Makeup > Concealer": ["concealer"],
        "Makeup > Face Makeup > Foundation": ["base", "coverage", "foundation"],
        "Makeup > Face Makeup > Powder": ["powder"],
        "Makeup > Lip Products": ["lip products", "products"],
        "Makeup > Lip Products > Lip Gloss": ["gloss", "lip gloss"],
        "Makeup > Lip Products > Lip Liner": ["liner", "lip liner"],
        "Makeup > Lip Products > Lipstick": ["gloss", "lip", "lipstick", "matte"],
        "Medical": ["medical"],
        "Medical > First Aid": ["first", "first aid"],
        "Medical > First Aid > Antiseptic": ["antiseptic"],
        "Medical > First Aid > Bandages": ["bandages"],
        "Medical > Pain Relief": ["pain", "pain relief", "relief"],
        "Medical > Pain Relief > Painkillers": ["painkillers"],
        "Medical > Vitamins & Supplements": ["& supplements", "supplements", "vitamins", "vitamins &", "vitamins & supplements"],
        "Medical > Vitamins & Supplements > Multivitamins": ["multivitamins"],
        "Medical > Vitamins & Supplements > Omega Supplements": ["omega", "omega supplements", "supplements"],
        "Personal Care": ["care", "personal", "personal care"],
        "Personal Care > Body Care": ["body", "body care", "care"],
        "Personal Care > Body Care > Body Lotion": ["body", "body lotion", "lotion"],
        "Personal Care > Body Care > Body Wash": ["body", "body wash", "wash"],
        "Personal Care > Oral Care": ["care", "oral", "oral care"],
        "Personal Care > Oral Care > Mouthwash": ["mouthwash"],
        "Personal Care > Oral Care > Toothbrushes": ["toothbrushes"],
        "Personal Care > Oral Care > Toothpaste": ["toothpaste"],
        "Personal Care > Shaving": ["shaving"],
        "Personal Care > Shaving > Razors": ["razors"],
        "Personal Care > Shaving > Shaving Cream": ["cream", "shaving", "shaving cream"],
        "Skincare": ["skincare"],
        "Skincare > Facial Cleansers": ["cleanser", "cleansers", "cleansing", "face wash", "facial", "facial cleansers"],
        "Skincare > Facial Cleansers > Face Wash": ["cleanser", "cleansing", "face", "face wash", "wash"],
        "Skincare > Facial Cleansers > Micellar Water": ["cleanser", "cleansing", "face wash", "micellar", "micellar water", "water"],
        "Skincare > Masks & Treatments": ["& treatments", "masks", "masks &", "masks & treatments", "treatments"],
        "Skincare > Masks & Treatments > Peel-Off Masks": ["masks", "peel-off", "peel-off masks"],
        "Skincare > Masks & Treatments > Sheet Masks": ["masks", "sheet", "sheet masks"],
        "Skincare > Moisturisers": ["cream", "lotion", "moisturiser", "moisturisers", "moisturizer"],
        "Skincare > Moisturisers > Day Cream": ["cream", "day cream", "lotion", "moisturiser", "moisturizer"],
        "Skincare > Moisturisers > Night Cream": ["cream", "lotion", "moisturiser", "moisturizer", "night", "night cream"],
        "Skincare > Serums": ["serums"],
        "Skincare > Serums > Hyaluronic Acid": ["acid", "hyaluronic", "hyaluronic acid"],
        "Skincare > Serums > Vitamin C Serum": ["c serum", "serum", "vitamin", "vitamin c", "vitamin c serum"],
        "Skincare > Sun Care": ["care", "sun care"],
        "Skincare > Sun Care > After Sun": ["after", "after sun"],
        "Skincare > Sun Care > Sunscreen": ["sunscreen"],
    },
    "Home & Garden": {
        "Bathroom": ["bathroom"],
        "Bathroom > Bathroom Storage": ["bathroom", "bathroom storage", "storage"],
        "Bathroom > Bathroom Storage > Bathroom Cabinets": ["bathroom", "bathroom cabinets", "cabinets"],
        "Bathroom > Bathroom Storage > Shelving": ["shelving"],
        "Bathroom > Towels": ["towels"],
        "Bathroom > Towels > Bath Towels": ["bath", "bath towels", "towels"],
        "Bathroom > Towels > Hand Towels": ["hand", "hand towels", "towels"],
        "Bedding": ["bedding", "duvet", "linen", "quilt", "sheets"],
        "Bedding > Bed Linen": ["bed linen", "bedding", "duvet", "linen", "quilt", "sheets"],
        "Bedding > Bed Linen > Bed Sheets": ["bed sheets", "bedding", "duvet", "linen", "quilt", "sheets"],
        "Bedding > Bed Linen > Duvet Covers": ["bedding", "covers", "duvet", "duvet covers", "linen", "quilt", "sheets"],
        "Bedding > Duvets & Pillows": ["& pillows", "bedding", "duvet", "duvets", "duvets &", "duvets & pillows", "linen", "pillows", "quilt", "sheets"],
        "Bedding > Duvets & Pillows > Duvets": ["bedding", "duvet", "duvets", "linen", "quilt", "sheets"],
        "Bedding > Duvets & Pillows > Pillows": ["bedding", "duvet", "linen", "pillows", "quilt", "sheets"],
        "Furniture": ["furniture"],
        "Furniture > Bedroom": ["bedroom"],
        "Furniture > Bedroom > Beds": ["beds"],
        "Furniture > Bedroom > Bedside Tables": ["bedside", "bedside tables", "tables"],
        "Furniture > Bedroom > Wardrobes": ["wardrobes"],
        "Furniture > Dining Room": ["dining", "dining room", "room"],
        "Furniture > Dining Room > Dining Chairs": ["chairs", "dining", "dining chairs"],
        "Furniture > Dining Room > Dining Tables": ["dining", "dining tables", "tables"],
        "Furniture > Living Room": ["living", "living room", "room"],
        "Furniture > Living Room > Coffee Tables": ["coffee", "coffee tables", "tables"],
        "Furniture > Living Room > Sofas": ["sofas"],
        "Furniture > Living Room > TV Stands": ["stands", "tv stands"],
        "Furniture > Office": ["office"],
        "Furniture > Office > Desks": ["desks"],
        "Furniture > Office > Office Chairs": ["chairs", "office", "office chairs"],
        "Garden": ["garden"],
        "Garden > BBQ & Outdoor Cooking": ["& outdoor", "bbq &", "bbq & outdoor cooking", "cooking", "outdoor", "outdoor cooking"],
        "Garden > BBQ & Outdoor Cooking > Charcoal BBQs": ["bbqs", "charcoal", "charcoal bbqs"],
        "Garden > BBQ & Outdoor Cooking > Gas BBQs": ["bbqs", "gas bbqs"],
        "Garden > Garden Tools": ["garden", "garden tools", "hoe", "rake", "spade", "tools", "trowel"],
        "Garden > Garden Tools > Hand Tools": ["hand", "hand tools", "hoe", "rake", "spade", "tools", "trowel"],
        "Garden > Garden Tools > Hedge Trimmers": ["hedge", "hedge trimmers", "hoe", "rake", "spade", "trimmers", "trowel"],
        "Garden > Garden Tools > Lawn Mowers": ["hoe", "lawn", "lawn mowers", "mowers", "rake", "spade", "trowel"],
        "Garden > Outdoor Furniture": ["outdoor", "outdoor furniture"],
        "Garden > Outdoor Furniture > Garden Chairs": ["chairs", "garden", "garden chairs"],
        "Garden > Outdoor Furniture > Garden Tables": ["garden", "garden tables", "tables"],
        "Garden > Outdoor Furniture > Parasols": ["parasols"],
        "Garden > Plants & Seeds": ["& seeds", "flower", "plant", "plants", "plants &", "plants & seeds", "seed", "seeds", "tree"],
        "Garden > Plants & Seeds > Indoor Plants": ["flower", "indoor", "indoor plants", "plant", "plants", "seed", "tree"],
        "Garden > Plants & Seeds > Seeds": ["flower", "plant", "seed", "seeds", "tree"],
        "Home Decor": ["decor", "home", "home decor"],
        "Home Decor > Curtains & Blinds": ["& blinds", "blinds", "curtains", "curtains &", "curtains & blinds"],
        "Home Decor > Curtains & Blinds > Blinds": ["blinds"],
        "Home Decor > Curtains & Blinds > Curtains": ["curtains"],
        "Home Decor > Mirrors": ["mirrors"],
        "Home Decor > Mirrors > Wall Mirrors": ["mirrors", "wall", "wall mirrors"],
        "Home Decor > Rugs & Carpets": ["& carpets", "carpets", "rugs", "rugs &", "rugs & carpets"],
        "Home Decor > Rugs & Carpets > Area Rugs": ["area", "area rugs", "rugs"],
        "Home Decor > Rugs & Carpets > Runners": ["runners"],
        "Home Decor > Wall Art": ["wall", "wall art"],
        "Home Decor > Wall Art > Canvas Prints": ["canvas", "canvas prints", "prints"],
        "Home Decor > Wall Art > Photo Frames": ["frames", "photo", "photo frames"],
        "Kitchen & Dining": ["& dining", "dining", "kitchen", "kitchen &", "kitchen & dining"],
        "Kitchen & Dining > Cookware": ["cookware", "frying pan", "pan", "pot", "saucepan"],
        "Kitchen & Dining > Cookware > Bakeware": ["bakeware", "frying pan", "pan", "pot", "saucepan"],
        "Kitchen & Dining > Cookware > Pans": ["frying pan", "pan", "pans", "pot", "saucepan"],
        "Kitchen & Dining > Cookware > Pots": ["frying pan", "pan", "pot", "pots", "saucepan"],
        "Kitchen & Dining > Kitchen Storage": ["kitchen", "kitchen storage", "storage"],
        "Kitchen & Dining > Kitchen Storage > Food Containers": ["containers", "food containers"],
        "Kitchen & Dining > Kitchen Storage > Spice Racks": ["racks", "spice", "spice racks"],
        "Kitchen & Dining > Tableware": ["tableware"],
        "Kitchen & Dining > Tableware > Cutlery": ["cutlery", "fork", "knife", "spoon"],
        "Kitchen & Dining > Tableware > Glasses": ["glasses"],
        "Kitchen & Dining > Tableware > Plates": ["plates"],
        "Lighting": ["lighting"],
        "Lighting > Ceiling Lights": ["ceiling", "ceiling lights", "lights"],
        "Lighting > Ceiling Lights > Chandeliers": ["chandeliers"],
        "Lighting > Ceiling Lights > Pendant Lights": ["lights", "pendant", "pendant lights"],
        "Lighting > Lamps": ["lamps"],
        "Lighting > Lamps > Floor Lamps": ["floor", "floor lamps", "lamps"],
        "Lighting > Lamps > Table Lamps": ["lamps", "table", "table lamps"],
        "Lighting > Outdoor Lighting": ["lighting", "outdoor", "outdoor lighting"],
        "Lighting > Outdoor Lighting > Garden Lights": ["garden", "garden lights", "lights"],
        "Pillows": ["bamboo", "cushion", "memory foam", "neck pillow", "orthopaedic", "pillow", "pillows", "sleeping pillow"],
    },
    "Luggage & Bags": {
        "Backpacks": ["backpack", "backpacks", "bag", "rucksack"],
        "Backpacks > Casual Backpacks": ["backpack", "backpacks", "bag", "casual", "casual backpacks", "rucksack"],
        "Backpacks > Casual Backpacks > Day Packs": ["backpack", "bag", "day packs", "packs", "rucksack"],
        "Backpacks > Casual Backpacks > School Backpacks": ["backpack", "backpacks", "bag", "rucksack", "school", "school backpacks"],
        "Backpacks > Hiking Backpacks": ["backpack", "backpacks", "bag", "hiking", "hiking backpacks", "rucksack"],
        "Backpacks > Hiking Backpacks > Hydration Packs": ["backpack", "bag", "hydration", "hydration packs", "packs", "rucksack"],
        "Backpacks > Hiking Backpacks > Trekking Backpacks": ["backpack", "backpacks", "bag", "rucksack", "trekking", "trekking backpacks"],
        "Backpacks > Laptop Backpacks": ["backpack", "backpacks", "bag", "laptop", "laptop backpacks", "rucksack"],
        "Backpacks > Laptop Backpacks > Business Backpacks": ["backpack", "backpacks", "bag", "business", "business backpacks", "rucksack"],
        "Business Bags": ["business", "business bags"],
        "Business Bags > Briefcases": ["briefcases"],
        "Business Bags > Briefcases > Leather Briefcases": ["briefcases", "leather", "leather briefcases"],
        "Business Bags > Briefcases > Soft Briefcases": ["briefcases", "soft", "soft briefcases"],
        "Business Bags > Laptop Bags": ["laptop", "laptop bags"],
        "Business Bags > Laptop Bags > Laptop Sleeves": ["laptop", "laptop sleeves", "sleeves"],
        "Business Bags > Laptop Bags > Messenger Bags": ["messenger", "messenger bags"],
        "Handbags": ["handbag", "handbags", "purse", "tote"],
        "Handbags > Clutches": ["clutches", "handbag", "purse", "tote"],
        "Handbags > Clutches > Envelope Clutches": ["clutches", "envelope", "envelope clutches", "handbag", "purse", "tote"],
        "Handbags > Clutches > Evening Clutches": ["clutches", "evening", "evening clutches", "handbag", "purse", "tote"],
        "Handbags > Shoulder Bags": ["handbag", "purse", "shoulder", "shoulder bags", "tote"],
        "Handbags > Shoulder Bags > Crossbody Bags": ["crossbody", "crossbody bags", "handbag", "purse", "tote"],
        "Handbags > Shoulder Bags > Hobo Bags": ["handbag", "hobo", "hobo bags", "purse", "tote"],
        "Handbags > Tote Bags": ["handbag", "purse", "tote", "tote bags"],
        "Handbags > Tote Bags > Canvas Totes": ["canvas", "canvas totes", "handbag", "purse", "tote", "totes"],
        "Handbags > Tote Bags > Leather Totes": ["handbag", "leather", "leather totes", "purse", "tote", "totes"],
        "Luggage": ["cabin", "carry on", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Luggage Sets": ["cabin", "carry on", "hard shell", "luggage", "luggage sets", "roller", "sets", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Luggage Sets > 2-Piece Sets": ["2-piece", "2-piece sets", "cabin", "carry on", "hard shell", "luggage", "roller", "sets", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Luggage Sets > 3-Piece Sets": ["3-piece", "3-piece sets", "cabin", "carry on", "hard shell", "luggage", "roller", "sets", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Suitcases": ["cabin", "carry on", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Suitcases > Cabin Luggage": ["cabin", "cabin luggage", "carry on", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Suitcases > Large Suitcases": ["cabin", "carry on", "hard shell", "large suitcases", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Suitcases > Medium Suitcases": ["cabin", "carry on", "hard shell", "luggage", "medium suitcases", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Travel Bags": ["cabin", "carry on", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "travel", "travel bags", "trolley"],
        "Luggage > Travel Bags > Duffel Bags": ["cabin", "carry on", "duffel", "duffel bags", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Travel Bags > Garment Bags": ["cabin", "carry on", "garment", "garment bags", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Luggage > Travel Bags > Weekend Bags": ["cabin", "carry on", "hard shell", "luggage", "roller", "spinner", "suitcase", "suitcases", "trolley", "weekend", "weekend bags"],
        "Sports Bags": ["sports", "sports bags"],
        "Sports Bags > Gym Bags": ["gym bags"],
        "Sports Bags > Gym Bags > Drawstring Bags": ["drawstring", "drawstring bags"],
        "Sports Bags > Gym Bags > Duffel Gym Bags": ["duffel", "duffel gym", "duffel gym bags", "gym bags"],
        "Sports Bags > Sports-Specific Bags": ["sports-specific", "sports-specific bags"],
        "Sports Bags > Sports-Specific Bags > Golf Bags": ["golf", "golf bags"],
        "Sports Bags > Sports-Specific Bags > Tennis Bags": ["tennis", "tennis bags"],
        "Travel Accessories": ["travel", "travel accessories"],
        "Travel Accessories > Travel Organisers": ["organisers", "travel", "travel organisers"],
        "Travel Accessories > Travel Organisers > Packing Cubes": ["cubes", "packing", "packing cubes"],
        "Travel Accessories > Travel Organisers > Toiletry Bags": ["toiletry", "toiletry bags"],
        "Travel Accessories > Travel Security": ["security", "travel", "travel security"],
        "Travel Accessories > Travel Security > Luggage Locks": ["cabin", "carry on", "hard shell", "locks", "luggage", "luggage locks", "roller", "spinner", "suitcase", "suitcases", "trolley"],
        "Travel Accessories > Travel Security > Luggage Tags": ["cabin", "carry on", "hard shell", "luggage", "luggage tags", "roller", "spinner", "suitcase", "suitcases", "tags", "trolley"],
        "Wallets & Purses": ["& purses", "purses", "wallets", "wallets &", "wallets & purses"],
        "Wallets & Purses > Men's Wallets": ["mens", "mens wallets", "wallets"],
        "Wallets & Purses > Men's Wallets > Bi-fold Wallets": ["bi-fold", "bi-fold wallets", "wallets"],
        "Wallets & Purses > Men's Wallets > Tri-fold Wallets": ["tri-fold", "tri-fold wallets", "wallets"],
        "Wallets & Purses > Women's Wallets": ["wallets", "womens", "womens wallets"],
        "Wallets & Purses > Women's Wallets > Card Holders": ["card", "card holders", "holders"],
        "Wallets & Purses > Women's Wallets > Long Wallets": ["long", "long wallets", "wallets"],
    },
    "Party & Celebration": {
        "Gift Giving": ["gift", "gift giving", "giving"],
        "Gift Giving > Gift Cards": ["cards", "gift", "gift cards"],
        "Gift Giving > Gift Cards > Experience Gift Cards": ["cards", "experience", "experience gift", "experience gift cards", "gift", "gift cards"],
        "Gift Giving > Gift Cards > Store Gift Cards": ["cards", "gift", "gift cards", "store", "store gift", "store gift cards"],
        "Gift Giving > Gift Wrap": ["gift", "gift wrap", "wrap", "wrapping paper"],
        "Gift Giving > Gift Wrap > Gift Bags": ["gift", "gift bags", "gift wrap", "wrap", "wrapping paper"],
        "Gift Giving > Gift Wrap > Wrapping Paper": ["gift wrap", "paper", "wrap", "wrapping", "wrapping paper"],
        "Party Supplies": ["party", "party supplies"],
        "Party Supplies > Balloons": ["balloon", "balloons"],
        "Party Supplies > Balloons > Balloon Arches": ["arches", "balloon", "balloon arches", "balloons"],
        "Party Supplies > Balloons > Foil Balloons": ["balloon", "balloons", "foil", "foil balloons"],
        "Party Supplies > Balloons > Latex Balloons": ["balloon", "balloons", "latex", "latex balloons"],
        "Party Supplies > Banners & Garlands": ["& garlands", "banners", "banners &", "banners & garlands", "garlands"],
        "Party Supplies > Banners & Garlands > Celebration Bunting": ["bunting", "celebration", "celebration bunting"],
        "Party Supplies > Banners & Garlands > Happy Birthday Banners": ["banners", "birthday", "birthday banners", "happy", "happy birthday", "happy birthday banners"],
        "Party Supplies > Party Decorations": ["banner", "decoration", "decorations", "party", "party decorations", "streamer"],
        "Party Supplies > Party Decorations > Centrepieces": ["banner", "centrepieces", "decoration", "streamer"],
        "Party Supplies > Party Decorations > Confetti": ["banner", "confetti", "decoration", "streamer"],
        "Party Supplies > Party Decorations > Streamers": ["banner", "decoration", "streamer", "streamers"],
        "Party Supplies > Party Favours": ["favours", "party", "party favours"],
        "Party Supplies > Party Favours > Goodie Bags": ["goodie", "goodie bags"],
        "Party Supplies > Party Favours > Party Hats": ["hats", "party", "party hats"],
        "Party Supplies > Party Tableware": ["party", "party tableware", "tableware"],
        "Party Supplies > Party Tableware > Napkins": ["napkins"],
        "Party Supplies > Party Tableware > Party Cups": ["cups", "party", "party cups"],
        "Party Supplies > Party Tableware > Party Plates": ["party", "party plates", "plates"],
        "Seasonal Decorations": ["decorations", "seasonal", "seasonal decorations"],
        "Seasonal Decorations > Christmas Decorations": ["christmas", "christmas decorations", "decorations"],
        "Seasonal Decorations > Christmas Decorations > Christmas Lights": ["christmas", "christmas lights", "lights"],
        "Seasonal Decorations > Christmas Decorations > Christmas Ornaments": ["christmas", "christmas ornaments", "ornaments"],
        "Seasonal Decorations > Christmas Decorations > Christmas Trees": ["christmas", "christmas trees", "trees"],
        "Seasonal Decorations > Easter Decorations": ["decorations", "easter", "easter decorations"],
        "Seasonal Decorations > Easter Decorations > Easter Baskets": ["baskets", "easter", "easter baskets"],
        "Seasonal Decorations > Easter Decorations > Easter Eggs": ["easter", "easter eggs", "eggs"],
        "Seasonal Decorations > Halloween Decorations": ["decorations", "halloween", "halloween decorations"],
        "Seasonal Decorations > Halloween Decorations > Halloween Costumes": ["costumes", "halloween", "halloween costumes"],
        "Seasonal Decorations > Halloween Decorations > Halloween Props": ["halloween", "halloween props", "props"],
        "Wedding Supplies": ["wedding", "wedding supplies"],
        "Wedding Supplies > Wedding Decorations": ["decorations", "wedding", "wedding decorations"],
        "Wedding Supplies > Wedding Decorations > Wedding Bunting": ["bunting", "wedding", "wedding bunting"],
        "Wedding Supplies > Wedding Decorations > Wedding Centrepieces": ["centrepieces", "wedding", "wedding centrepieces"],
        "Wedding Supplies > Wedding Favours": ["favours", "wedding", "wedding favours"],
        "Wedding Supplies > Wedding Favours > Guest Gifts": ["gifts", "guest", "guest gifts"],
        "Wedding Supplies > Wedding Invitations": ["invitations", "wedding", "wedding invitations"],
        "Wedding Supplies > Wedding Invitations > Invitation Sets": ["invitation", "invitation sets", "sets"],
    },
    "Pets": {
        "Bird Supplies": ["bird", "bird supplies"],
        "Bird Supplies > Bird Cages": ["bird", "bird cages", "cages"],
        "Bird Supplies > Bird Cages > Parakeet Cages": ["cages", "parakeet", "parakeet cages"],
        "Bird Supplies > Bird Food": ["bird", "bird food"],
        "Bird Supplies > Bird Food > Bird Treats": ["bird", "bird treats", "treats"],
        "Bird Supplies > Bird Food > Seed Mixes": ["mixes", "seed", "seed mixes"],
        "Bird Supplies > Bird Toys": ["bird", "bird toys"],
        "Bird Supplies > Bird Toys > Perches & Swings": ["& swings", "perches", "perches &", "perches & swings", "swings"],
        "Cat Supplies": ["cat supplies"],
        "Cat Supplies > Cat Beds & Furniture": ["& furniture", "beds", "beds &", "cat beds", "cat beds & furniture"],
        "Cat Supplies > Cat Beds & Furniture > Cat Beds": ["beds", "cat beds"],
        "Cat Supplies > Cat Beds & Furniture > Cat Trees": ["cat condo", "cat tower", "cat tree", "cat trees", "climbing", "scratch post", "scratching post", "sisal", "trees"],
        "Cat Supplies > Cat Food": ["adult cat", "cat food", "dry food", "fancy feast", "felix", "kitten", "purina", "wet food", "whiskas"],
        "Cat Supplies > Cat Food > Cat Treats": ["adult cat", "cat treats", "dry food", "fancy feast", "felix", "kitten", "purina", "treats", "wet food", "whiskas"],
        "Cat Supplies > Cat Food > Dry Cat Food": ["adult cat", "cat food", "dry cat", "dry cat food", "dry food", "fancy feast", "felix", "kitten", "purina", "wet food", "whiskas"],
        "Cat Supplies > Cat Food > Wet Cat Food": ["adult cat", "cat food", "dry food", "fancy feast", "felix", "kitten", "purina", "wet cat", "wet cat food", "wet food", "whiskas"],
        "Cat Supplies > Cat Litter": ["cat litter", "litter"],
        "Cat Supplies > Cat Litter > Clumping Litter": ["clumping", "clumping litter", "litter"],
        "Cat Supplies > Cat Litter > Crystal Litter": ["crystal", "crystal litter", "litter"],
        "Cat Supplies > Cat Toys": ["cat toys", "catnip", "feather", "laser", "mouse toy"],
        "Cat Supplies > Cat Toys > Catnip Toys": ["catnip", "catnip toys", "feather", "laser", "mouse toy"],
        "Cat Supplies > Cat Toys > Interactive Cat Toys": ["cat toys", "catnip", "feather", "interactive", "interactive cat", "interactive cat toys", "laser", "mouse toy"],
        "Dog Supplies": ["dog supplies"],
        "Dog Supplies > Dog Beds & Furniture": ["& furniture", "beds", "beds &", "dog beds", "dog beds & furniture"],
        "Dog Supplies > Dog Beds & Furniture > Dog Beds": ["beds", "dog beds"],
        "Dog Supplies > Dog Beds & Furniture > Dog Crates": ["crates", "dog crates"],
        "Dog Supplies > Dog Collars & Leads": ["& leads", "collar", "collars", "collars &", "dog collars", "dog collars & leads", "harness", "lead", "leads", "leash"],
        "Dog Supplies > Dog Collars & Leads > Dog Collars": ["collar", "collars", "dog collars", "harness", "lead", "leash"],
        "Dog Supplies > Dog Collars & Leads > Dog Harnesses": ["collar", "dog harnesses", "harness", "harnesses", "lead", "leash"],
        "Dog Supplies > Dog Food": ["adult dog", "dog food", "dry food", "hills", "kibble", "pedigree", "puppy", "purina", "royal canin", "wet food"],
        "Dog Supplies > Dog Food > Dog Treats": ["adult dog", "dog treats", "dry food", "hills", "kibble", "pedigree", "puppy", "purina", "royal canin", "treats", "wet food"],
        "Dog Supplies > Dog Food > Dry Dog Food": ["adult dog", "dog food", "dry dog", "dry dog food", "dry food", "hills", "kibble", "pedigree", "puppy", "purina", "royal canin", "wet food"],
        "Dog Supplies > Dog Food > Wet Dog Food": ["adult dog", "dog food", "dry food", "hills", "kibble", "pedigree", "puppy", "purina", "royal canin", "wet dog", "wet dog food", "wet food"],
        "Dog Supplies > Dog Grooming": ["dog grooming", "grooming"],
        "Dog Supplies > Dog Grooming > Dog Brushes": ["brushes", "dog brushes"],
        "Dog Supplies > Dog Grooming > Dog Shampoo": ["dog shampoo", "shampoo"],
        "Dog Supplies > Dog Toys": ["ball", "chew toy", "dog toys", "kong", "plush toy", "rope toy"],
        "Dog Supplies > Dog Toys > Chew Toys": ["ball", "chew", "chew toy", "chew toys", "kong", "plush toy", "rope toy"],
        "Dog Supplies > Dog Toys > Fetch Toys": ["ball", "chew toy", "fetch", "fetch toys", "kong", "plush toy", "rope toy"],
        "Fish & Aquarium": ["& aquarium", "aqua one", "aquarium", "filter", "fish", "fish &", "fish & aquarium", "heater", "pump", "tank"],
        "Fish & Aquarium > Aquarium Filters": ["aqua one", "aquarium", "aquarium filters", "filter", "filters", "heater", "pump", "tank"],
        "Fish & Aquarium > Aquarium Filters > Internal Filters": ["aqua one", "filter", "filters", "heater", "internal", "internal filters", "pump", "tank"],
        "Fish & Aquarium > Aquariums & Tanks": ["& tanks", "aqua one", "aquariums", "aquariums &", "aquariums & tanks", "filter", "heater", "pump", "tank", "tanks"],
        "Fish & Aquarium > Aquariums & Tanks > Freshwater Tanks": ["aqua one", "filter", "freshwater", "freshwater tanks", "heater", "pump", "tank", "tanks"],
        "Fish & Aquarium > Aquariums & Tanks > Marine Tanks": ["aqua one", "filter", "heater", "marine", "marine tanks", "pump", "tank", "tanks"],
        "Fish & Aquarium > Fish Food": ["aqua one", "filter", "fish", "fish food", "heater", "pump", "tank"],
        "Fish & Aquarium > Fish Food > Tropical Fish Food": ["aqua one", "filter", "fish", "fish food", "heater", "pump", "tank", "tropical", "tropical fish", "tropical fish food"],
        "Reptile Supplies": ["reptile", "reptile supplies"],
        "Reptile Supplies > Reptile Food": ["reptile", "reptile food"],
        "Reptile Supplies > Reptile Food > Live Food": ["live", "live food"],
        "Reptile Supplies > Reptile Habitats": ["habitats", "reptile", "reptile habitats"],
        "Reptile Supplies > Reptile Habitats > Terrariums": ["terrariums"],
        "Reptile Supplies > Reptile Heating": ["heating", "reptile", "reptile heating"],
        "Reptile Supplies > Reptile Heating > Heat Lamps": ["heat", "heat lamps", "lamps"],
        "Small Animal Supplies": ["animal", "animal supplies", "small animal", "small animal supplies"],
        "Small Animal Supplies > Small Animal Bedding": ["animal", "animal bedding", "bedding", "small animal", "small animal bedding"],
        "Small Animal Supplies > Small Animal Bedding > Wood Shavings": ["shavings", "wood", "wood shavings"],
        "Small Animal Supplies > Small Animal Cages": ["animal", "animal cages", "cages", "small animal", "small animal cages"],
        "Small Animal Supplies > Small Animal Cages > Rabbit Hutches": ["hutches", "rabbit", "rabbit hutches"],
        "Small Animal Supplies > Small Animal Food": ["animal", "animal food", "small animal", "small animal food"],
        "Small Animal Supplies > Small Animal Food > Hamster Food": ["hamster", "hamster food"],
        "Small Animal Supplies > Small Animal Food > Rabbit Food": ["rabbit", "rabbit food"],
    },
    "Sporting Goods": {
        "Athletic Shoes": ["adidas", "air max", "athletic shoes", "jogging", "marathon", "nike", "running", "running shoes", "sneakers", "sports shoes", "trainers"],
        "Fitness & Gym": ["& gym", "fitness", "fitness &", "fitness & gym"],
        "Fitness & Gym > Cardio Equipment": ["cardio", "cardio equipment", "equipment"],
        "Fitness & Gym > Cardio Equipment > Exercise Bikes": ["bikes", "exercise", "exercise bike", "exercise bikes", "spin bike", "stationary bike"],
        "Fitness & Gym > Cardio Equipment > Rowing Machines": ["machines", "rowing", "rowing machines"],
        "Fitness & Gym > Cardio Equipment > Treadmills": ["running machine", "treadmill", "treadmills"],
        "Fitness & Gym > Strength Training": ["strength", "strength training", "training"],
        "Fitness & Gym > Strength Training > Dumbbells": ["dumbbell", "dumbbells", "kettlebell", "weight"],
        "Fitness & Gym > Strength Training > Kettlebells": ["kettlebells"],
        "Fitness & Gym > Strength Training > Weight Benches": ["benches", "weight", "weight benches"],
        "Fitness & Gym > Yoga & Pilates": ["& pilates", "pilates", "yoga", "yoga &", "yoga & pilates"],
        "Fitness & Gym > Yoga & Pilates > Foam Rollers": ["foam", "foam rollers", "rollers"],
        "Fitness & Gym > Yoga & Pilates > Resistance Bands": ["bands", "resistance", "resistance bands"],
        "Fitness & Gym > Yoga & Pilates > Yoga Mats": ["mats", "yoga", "yoga mats"],
        "Golf": ["golf"],
        "Golf > Golf Bags": ["golf", "golf bags"],
        "Golf > Golf Bags > Cart Bags": ["cart", "cart bags"],
        "Golf > Golf Balls": ["balls", "golf", "golf balls"],
        "Golf > Golf Balls > Premium Golf Balls": ["balls", "golf", "golf balls", "premium golf", "premium golf balls"],
        "Golf > Golf Clubs": ["clubs", "golf", "golf clubs"],
        "Golf > Golf Clubs > Drivers": ["drivers"],
        "Golf > Golf Clubs > Irons": ["irons"],
        "Golf > Golf Clubs > Putters": ["putters"],
        "Outdoor Recreation": ["outdoor", "outdoor recreation", "recreation"],
        "Outdoor Recreation > Camping": ["camping"],
        "Outdoor Recreation > Camping > Camping Chairs": ["camping", "camping chairs", "chairs"],
        "Outdoor Recreation > Camping > Sleeping Bags": ["sleeping", "sleeping bags"],
        "Outdoor Recreation > Camping > Tents": ["tents"],
        "Outdoor Recreation > Cycling": ["cycling"],
        "Outdoor Recreation > Cycling > Cycling Helmets": ["cycling", "cycling helmets", "helmets"],
        "Outdoor Recreation > Cycling > Electric Bikes": ["bikes", "electric", "electric bikes"],
        "Outdoor Recreation > Cycling > Mountain Bikes": ["bikes", "mountain", "mountain bikes"],
        "Outdoor Recreation > Cycling > Road Bikes": ["bikes", "road", "road bikes"],
        "Outdoor Recreation > Hiking": ["hiking"],
        "Outdoor Recreation > Hiking > Backpacks": ["backpacks"],
        "Outdoor Recreation > Hiking > Hiking Boots": ["boots", "hiking", "hiking boots"],
        "Racquet Sports": ["racquet", "racquet sports", "sports"],
        "Racquet Sports > Badminton": ["badminton"],
        "Racquet Sports > Badminton > Badminton Racquets": ["badminton", "badminton racquets", "racquets"],
        "Racquet Sports > Badminton > Shuttlecocks": ["shuttlecocks"],
        "Racquet Sports > Tennis": ["ball", "racket", "racquet", "tennis"],
        "Racquet Sports > Tennis > Tennis Balls": ["ball", "balls", "racket", "racquet", "tennis", "tennis balls"],
        "Racquet Sports > Tennis > Tennis Racquets": ["ball", "racket", "racquet", "racquets", "tennis", "tennis racquets"],
        "Running Shoes": ["air max", "jogging shoes", "marathon shoes", "running shoes", "running trainers", "ultraboost"],
        "Team Sports": ["sports", "team", "team sports"],
        "Team Sports > Basketball": ["ball", "basketball", "hoop"],
        "Team Sports > Basketball > Basketball Hoops": ["ball", "basketball", "basketball hoops", "hoop", "hoops"],
        "Team Sports > Basketball > Basketballs": ["ball", "basketball", "basketballs", "hoop"],
        "Team Sports > Cricket": ["cricket"],
        "Team Sports > Cricket > Cricket Balls": ["balls", "cricket", "cricket balls"],
        "Team Sports > Cricket > Cricket Bats": ["bats", "cricket", "cricket bats"],
        "Team Sports > Football": ["ball", "football", "soccer"],
        "Team Sports > Football > Football Boots": ["ball", "boots", "football", "football boots", "soccer"],
        "Team Sports > Football > Football Goals": ["ball", "football", "football goals", "goals", "soccer"],
        "Team Sports > Football > Footballs": ["ball", "football", "footballs", "soccer"],
        "Team Sports > Rugby": ["rugby"],
        "Team Sports > Rugby > Rugby Balls": ["balls", "rugby", "rugby balls"],
        "Team Sports > Rugby > Rugby Boots": ["boots", "rugby", "rugby boots"],
        "Water Sports": ["sports", "water", "water sports"],
        "Water Sports > Kayaking": ["kayaking"],
        "Water Sports > Kayaking > Kayaks": ["kayaks"],
        "Water Sports > Kayaking > Paddles": ["paddles"],
        "Water Sports > Surfing": ["surfing"],
        "Water Sports > Surfing > Surfboards": ["surfboards"],
        "Water Sports > Surfing > Wetsuits": ["wetsuits"],
        "Water Sports > Swimming": ["swimming"],
        "Water Sports > Swimming > Goggles": ["goggles"],
        "Water Sports > Swimming > Swimwear": ["swimwear"],
        "Winter Sports": ["sports", "winter", "winter sports"],
        "Winter Sports > Skiing": ["skiing"],
        "Winter Sports > Skiing > Ski Boots": ["boots", "ski boots"],
        "Winter Sports > Skiing > Skis": ["skis"],
        "Winter Sports > Snowboarding": ["snowboarding"],
        "Winter Sports > Snowboarding > Snowboard Boots": ["boots", "snowboard", "snowboard boots"],
        "Winter Sports > Snowboarding > Snowboards": ["snowboards"],
    },
    "Toys": {
        "Action Figures": ["action", "action figures", "collectible", "figure", "figures", "figurine"],
        "Action Figures > Anime Figures": ["anime", "anime figures", "collectible", "figure", "figures", "figurine"],
        "Action Figures > Anime Figures > Collectible Figures": ["collectible", "collectible figures", "figure", "figures", "figurine"],
        "Action Figures > Movie & TV Figures": ["& tv", "collectible", "figure", "figures", "figurine", "movie", "movie &", "movie & tv figures", "tv figures"],
        "Action Figures > Movie & TV Figures > Star Wars Figures": ["collectible", "figure", "figures", "figurine", "star", "star wars", "star wars figures", "wars", "wars figures"],
        "Action Figures > Superhero Figures": ["collectible", "figure", "figures", "figurine", "superhero", "superhero figures"],
        "Action Figures > Superhero Figures > DC Figures": ["collectible", "dc figures", "figure", "figures", "figurine"],
        "Action Figures > Superhero Figures > Marvel Figures": ["collectible", "figure", "figures", "figurine", "marvel", "marvel figures"],
        "Building Toys": ["bricks", "building", "building blocks", "building toys", "construction", "lego"],
        "Building Toys > Building Blocks": ["blocks", "bricks", "building", "building blocks", "construction", "lego"],
        "Building Toys > Building Blocks > Magnetic Blocks": ["blocks", "bricks", "building blocks", "construction", "lego", "magnetic", "magnetic blocks"],
        "Building Toys > Building Blocks > Wooden Blocks": ["blocks", "bricks", "building blocks", "construction", "lego", "wooden", "wooden blocks"],
        "Building Toys > LEGO": ["bricks", "building blocks", "construction", "lego"],
        "Building Toys > LEGO > LEGO Sets": ["bricks", "building blocks", "construction", "lego", "lego sets", "sets"],
        "Building Toys > LEGO > LEGO Technic": ["bricks", "building blocks", "construction", "lego", "lego technic", "technic"],
        "Dolls & Accessories": ["& accessories", "barbie", "doll", "dollhouse", "dolls", "dolls &", "dolls & accessories"],
        "Dolls & Accessories > Baby Dolls": ["baby dolls", "barbie", "doll", "dollhouse", "dolls"],
        "Dolls & Accessories > Baby Dolls > Reborn Dolls": ["barbie", "doll", "dollhouse", "dolls", "reborn", "reborn dolls"],
        "Dolls & Accessories > Doll Playsets": ["barbie", "doll", "doll playsets", "dollhouse", "playsets"],
        "Dolls & Accessories > Doll Playsets > Doll Houses": ["barbie", "doll", "doll houses", "dollhouse", "houses"],
        "Dolls & Accessories > Fashion Dolls": ["barbie", "doll", "dollhouse", "dolls", "fashion", "fashion dolls"],
        "Dolls & Accessories > Fashion Dolls > Barbie Dolls": ["barbie", "barbie dolls", "doll", "dollhouse", "dolls"],
        "Dolls & Accessories > Fashion Dolls > Bratz Dolls": ["barbie", "bratz", "bratz dolls", "doll", "dollhouse", "dolls"],
        "Educational Toys": ["educational", "educational toys"],
        "Educational Toys > Learning Toys": ["learning", "learning toys"],
        "Educational Toys > Learning Toys > Alphabet Toys": ["alphabet", "alphabet toys"],
        "Educational Toys > Learning Toys > Number Toys": ["number", "number toys"],
        "Educational Toys > STEM Toys": ["stem", "stem toys"],
        "Educational Toys > STEM Toys > Coding Toys": ["coding", "coding toys"],
        "Educational Toys > STEM Toys > Science Kits": ["kits", "science", "science kits"],
        "Games & Puzzles": ["& puzzles", "1000 piece", "games", "games &", "games & puzzles", "jigsaw", "puzzle", "puzzles"],
        "Games & Puzzles > Board Games": ["board", "board games", "chess", "game", "games", "monopoly", "scrabble"],
        "Games & Puzzles > Board Games > Family Board Games": ["board", "board games", "chess", "family", "family board", "family board games", "game", "games", "monopoly", "scrabble"],
        "Games & Puzzles > Board Games > Strategy Games": ["chess", "game", "games", "monopoly", "scrabble", "strategy", "strategy games"],
        "Games & Puzzles > Card Games": ["1000 piece", "card", "card games", "games", "jigsaw", "puzzle"],
        "Games & Puzzles > Card Games > Trading Cards": ["1000 piece", "cards", "jigsaw", "puzzle", "trading", "trading cards"],
        "Games & Puzzles > Puzzles": ["1000 piece", "jigsaw", "puzzle", "puzzles"],
        "Games & Puzzles > Puzzles > 3D Puzzles": ["1000 piece", "3d puzzles", "jigsaw", "puzzle", "puzzles"],
        "Games & Puzzles > Puzzles > Jigsaw Puzzles": ["1000 piece", "jigsaw", "jigsaw puzzles", "puzzle", "puzzles"],
        "Outdoor Toys": ["outdoor", "outdoor toys"],
        "Outdoor Toys > Playsets": ["playsets"],
        "Outdoor Toys > Playsets > Sandpits": ["sandpits"],
        "Outdoor Toys > Playsets > Swing Sets": ["sets", "swing", "swing sets"],
        "Outdoor Toys > Ride-On Toys": ["ride-on", "ride-on toys"],
        "Outdoor Toys > Ride-On Toys > Electric Ride-Ons": ["electric", "electric ride-ons", "ride-ons"],
        "Outdoor Toys > Ride-On Toys > Tricycles": ["tricycles"],
        "Outdoor Toys > Sports Toys": ["sports", "sports toys"],
        "Outdoor Toys > Sports Toys > Football Goals": ["football", "football goals", "goals"],
        "Remote Control Toys": ["control", "control toys", "remote", "remote control", "remote control toys"],
        "Remote Control Toys > RC Cars": ["cars", "rc cars"],
        "Remote Control Toys > RC Cars > Off-Road RC Cars": ["cars", "off-road", "off-road rc", "off-road rc cars", "rc cars"],
        "Remote Control Toys > RC Drones": ["drones", "rc drones"],
        "Remote Control Toys > RC Drones > Camera Drones": ["camera drones", "drones"],
        "Remote Control Toys > RC Helicopters": ["helicopters", "rc helicopters"],
        "Remote Control Toys > RC Helicopters > Mini Helicopters": ["helicopters", "mini", "mini helicopters"],
        "Soft Toys": ["soft", "soft toys"],
        "Soft Toys > Stuffed Animals": ["animals", "stuffed", "stuffed animals"],
        "Soft Toys > Stuffed Animals > Animal Plush": ["animal", "animal plush", "plush"],
        "Soft Toys > Stuffed Animals > Character Plush": ["character", "character plush", "plush"],
        "Soft Toys > Teddy Bears": ["bears", "teddy", "teddy bears"],
        "Soft Toys > Teddy Bears > Classic Teddy Bears": ["bears", "classic teddy", "classic teddy bears", "teddy", "teddy bears"],
    },
}